package common.util.exceptions

class BadFunctionException(private val message: String = "") extends BadRelationException(message) {

}
